name: OpenWrt Firmware For x86_64

on:
  push:
    branches:
    - master

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - '.github/workflows/pipeline.yml'
#       - 'config'
#       - 'files'
#       - 'diy.sh'
#       - 'feeds.conf.default'
#   schedule:
#     - cron: '00 18 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clean up disk space
      run: |
        set -x
        ./action.sh cleanup
        ./action.sh init
        ./action.sh build
        ./action.sh artifact

    - name: Make the Artifact
      id: artifact
      run: |
        release_tag="$(date +%Y-%m-%d)"
        echo "##[set-output name=release_tag;]$release_tag"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.artifact.outputs.release_tag }}
        release_name: Auto Release ${{ steps.artifact.outputs.release_tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset(openwrt-x86-64-squashfs-img)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openwrt-x86-64-squashfs-img.zip
        asset_name: openwrt-x86-64-squashfs-img.zip
        asset_content_type: application/zip

    - name: Upload Release Asset(openwrt-x86-64-ext4-img)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openwrt-x86-64-ext4-img.zip
        asset_name: openwrt-x86-64-ext4-img.zip
        asset_content_type: application/zip

    - name: Upload Release Asset(openwrt-x86-64-squashfs-vmdk)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openwrt-x86-64-squashfs-vmdk.zip
        asset_name: openwrt-x86-64-squashfs-vmdk.zip
        asset_content_type: application/zip

    - name: Upload Release Asset(openwrt-x86-64-ext4-vmdk)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openwrt-x86-64-ext4-vmdk.zip
        asset_name: openwrt-x86-64-ext4-vmdk.zip
        asset_content_type: application/zip